### PR TITLE
Update express dependency to 3.2.x

### PR DESCRIPTION
**Pull request by ericf**
This updates Express to the latest version and also uses a less restrictive version.

### CODE REVIEW

**Comment by rgrove** [comment]
Thanks!

**Comment by ericf** [comment]
Worth a quick version bump and npm publish?

**Comment by rgrove** [comment]
Pretty sure @evocateur is planning to publish a release soon. Can you wait for that?

**Comment by evocateur** [comment]
I'm okay with a 0.2.x bump. My changes are going to necessitate a minor bump (0.3.0) simply due to the scope of added features/code.

**Comment by rgrove** [comment]
@evocateur Are you volunteering to update HISTORY.md? There've been a lot of changes since 0.2.1: https://github.com/rgrove/combohandler/compare/v0.2.1...master

**Comment by evocateur** [comment]
Hrm, yes, that's true, I suppose I am. I'll be doing that anyway for the `cluster-cli` PR, so I might as well do this as well.

**Comment by evocateur** [comment]
Historified, bumped, and published as `0.2.2`: https://npmjs.org/package/combohandler

**Pull request merged**
