### PR TITLE
Express 4.x

### PR DESCRIPTION
**Pull request by evocateur**
Increasingly, I feel that `lib/server` and the CLI executable should be separated from the rest of the library (`combohandler-server`?), as it is itself just a consumer of the middleware. It's burdening those whole only ever use the library as middleware with all of express, etc.

The changes herein are largely explained by the [Migrating from 3.x to 4.x](https://github.com/visionmedia/express/wiki/Migrating-from-3.x-to-4.x) wiki.

### CODE REVIEW

**Comment by akshayp** [comment]
@evocateur In addition to your changes I see this was merged in https://github.com/rgrove/combohandler/commit/9d61e3a4187f60d58a31c153300746bfd07887f9 but the package was never officially bumped up for express 4 support. Do you know when you plan on merging this in? I'd be happy to help too btw if there's something blocking you

**Comment by evocateur** [comment]
Oh, we should probably do that. I can get to it Monday.

**Comment by evocateur** [comment]
@akshayp Published in `combohandler` v0.4.0. Thanks for the reminder!

**Comment by akshayp** [comment]
:+1: Thanks for the quick turnaround

**Pull request merged**
